dataset_params:
  im_path: './generated_images'
  im_channels: 3
  im_size: 64
  name: 'ptt_faces'

diffusion_params:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02

ldm_params:
  down_channels: [64, 128, 256, 256]
  mid_channels: [256, 256]
  down_sample: [True, True, False]
  attn_down: [True, True, True]
  time_emb_dim: 256
  norm_channels: 32
  num_heads: 4
  conv_out_channels: 64
  num_down_layers: 2
  num_mid_layers: 2
  num_up_layers: 2

train_params:
  seed: 42
  batch_size: 4
  epochs: 1000
  lr: 0.0001
  checkpoint_every: 100
  sample_every: 10
  scheduler: cosine
  scheduler_eta_min: 0.000001
